### ISSUE TITLE
:bug: fix(bal-nav | bal-popup): First Popup is misaligned when opening for the first time

### ISSUE THREAD

**Issue by GinaBiondo** [baloise/design-system#1443] opened 2024-08-29 13:50 UTC
### Current Behavior

https://www.baloise.ch/de/privatkunden.html
When opening the phone popup in the navigation for the first time it is slightly misaligned. Closing and opening it again aligns it perfectly.
This is a minor issue!

### Expected Behavior

All popups should be aligned correctly all the time

### Steps to Reproduce

Use the navigation with meta buttons and popups. See https://www.baloise.ch/de/privatkunden.html

### Version

16.2.1

### Browsers

Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment] 2024-09-05 11:41
![Image](https://github.com/user-attachments/assets/7276b1d0-afd5-4162-b57d-876379604b75)

**Comment by hirsch88** [comment] 2024-12-05 11:57
cannot reproduce this issue, therefore we will close it

**Closed as completed by hirsch88** 2024-12-05 11:57 UTC
Labels: 🐛 bug
