### ISSUE TITLE
♿️ a11y(bal-radio | bal-checkbox): Inputs focusable

### ISSUE THREAD

**Issue by GinaBiondo** [baloise/design-system#1010] opened 2023-07-26 16:36 UTC
### Current Behavior

Currently the hidden Inputs inside bal-radio and bal-checkbox are focusable additionally to the component itself. This could cause weird behavior for keyboard and screenreader users.

### Expected Behavior

Only the component needed to trigger an event should be focusable

### Steps to Reproduce

regular usage of radio buttons and checkboxes

### Version

13.6.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yannickholzenkamp** [comment] 2024-09-05 12:57
Hi @GinaBiondo-aperto 

Discussed the issue in the Design-System team. According to @hirsch88 we only support the Google Chrome standard screenreader. 
This issue does not seem to be present in the Google Chrome screenreader (https://chromewebstore.google.com/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn?hl=de&utm_source=ext_sidebar).

Can you reproduce this issue with the Google Chrome screenreader?

We will close the issue for now. Please let us know in case we should re-open it.
Thanks!

**Closed as completed by yannickholzenkamp** 2024-09-05 12:57 UTC
Labels: 🐛 bug

**Comment by yannickholzenkamp** [comment] 2024-09-05 13:22
Hi @carolabes

We can't reproduce this issue with our screenreaders (see comment before).
Could you provide more information about the screenreader, browser etc. and re-open the issue in case it still exists?
Thank you!
